# wrangler.toml
name = "subtitles-api"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[env.production]
name = "subtitles-api-production"
